### ISSUE TITLE
MemoryError during download

### ISSUE THREAD

**Issue by j08lue** [sentinelsat/sentinelsat#150]
With `sentinelsat` 0.11 on Python 3.6, Windows 10 (64 bit), I got the following error
```
2017-08-09 09:41:12 INFO Downloading f1717a14-855b-404b-ace8-a8f4c30a20a8 to E:\S1\download\S1B_IW_GRDH_1SDV_20170806T165300_20170806T165325_006822_00C01B_6A6E.zip
Traceback (most recent call last):
  File "C:\Users\some_username\AppData\Local\Continuum\Miniconda2\envs\some_project\lib\site-packages\sentinelsat\sentinel.py", line 469, in _check_scihub_response
    msg = response.json()['error']['message']['value']
  File "C:\Users\some_username\AppData\Local\Continuum\Miniconda2\envs\some_project\lib\site-packages\requests\models.py", line 894, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\some_username\AppData\Local\Continuum\Miniconda2\envs\some_project\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\some_username\AppData\Local\Continuum\Miniconda2\envs\some_project\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\some_username\AppData\Local\Continuum\Miniconda2\envs\some_project\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\some_username\AppData\Local\Continuum\Miniconda2\envs\some_project\lib\site-packages\sentinelsat\sentinel.py", line 361, in download_all
    check_existing)
  File "C:\Users\some_username\AppData\Local\Continuum\Miniconda2\envs\some_project\lib\site-packages\sentinelsat\sentinel.py", line 307, in download
    product_info['downloaded_bytes'] = _download(product_info['url'], path, self.session, product_info['size'])
  File "C:\Users\some_username\AppData\Local\Continuum\Miniconda2\envs\some_project\lib\site-packages\sentinelsat\sentinel.py", line 619, in _download
    _check_scihub_response(r, test_json=False)
  File "C:\Users\some_username\AppData\Local\Continuum\Miniconda2\envs\some_project\lib\site-packages\sentinelsat\sentinel.py", line 471, in _check_scihub_response
    if not response.text.strip().startswith('{'):
  File "C:\Users\some_username\AppData\Local\Continuum\Miniconda2\envs\some_project\lib\site-packages\requests\models.py", line 854, in text
    encoding = self.apparent_encoding
  File "C:\Users\some_username\AppData\Local\Continuum\Miniconda2\envs\some_project\lib\site-packages\requests\models.py", line 724, in apparent_encoding
    return chardet.detect(self.content)['encoding']
  File "C:\Users\some_username\AppData\Local\Continuum\Miniconda2\envs\some_project\lib\site-packages\chardet\__init__.py", line 38, in detect
    detector.feed(byte_str)
  File "C:\Users\some_username\AppData\Local\Continuum\Miniconda2\envs\some_project\lib\site-packages\chardet\universaldetector.py", line 211, in feed
    if prober.feed(byte_str) == ProbingState.FOUND_IT:
  File "C:\Users\some_username\AppData\Local\Continuum\Miniconda2\envs\some_project\lib\site-packages\chardet\charsetgroupprober.py", line 71, in feed
    state = prober.feed(byte_str)
  File "C:\Users\some_username\AppData\Local\Continuum\Miniconda2\envs\some_project\lib\site-packages\chardet\hebrewprober.py", line 227, in feed
    byte_str = self.filter_high_byte_only(byte_str)
  File "C:\Users\some_username\AppData\Local\Continuum\Miniconda2\envs\some_project\lib\site-packages\chardet\charsetprober.py", line 63, in filter_high_byte_only
    buf = re.sub(b'([\x00-\x7F])+', b' ', buf)
  File "C:\Users\some_username\AppData\Local\Continuum\Miniconda2\envs\some_project\lib\re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
MemoryError
```
So first `response.json()` failed in [this line](https://github.com/sentinelsat/sentinelsat/blob/1ebb7b65fb6778ed61590726b952b77df8f2c698/sentinelsat/sentinel.py#L809) but we catch that.

And then `response.text()` from [this line](https://github.com/sentinelsat/sentinelsat/blob/1ebb7b65fb6778ed61590726b952b77df8f2c698/sentinelsat/sentinel.py#L811) went berserk.

The memory (32 GB, 16 GB free at the time) was never anywhere close to being maxed out, as far as I could see, but it is a rather old machine.

I have experienced this several times on one machine but cannot reproduce it on another.

While writing this it appears more and more likely that this was an issue related to the state of the
particular machine. But I will submit this report anyways and add to it if I find out more.

**Comment by valgur** [comment]
That's really odd. The bug seems to stem from `chardet` when `requests` tries to automagically determine the character encoding of the response. This is actually absolutely unnecessary since the response can be quite safely assumed to be in UTF-8 (if not straight ASCII). At least the XML-encoded responses include `<?xml version="1.0" encoding="utf-8"?>` and this most probably applies for JSON responses as well.

So a simple fix (and a minor performance improvement) would be to replace every `response.text` with `response.content.decode("utf8")`. Making sure it works correctly on Python 2 as well will be a minor source of pain here, though.

**Comment by Fernerkundung** [comment]
@j08lue has the error been fixed with #152?

**Comment by j08lue** [comment]
I have not experienced it in like 2000 downloads since. But has always been hard to reproduce:

> I wonder what the content of that response might have been.

I wondered about that too...

But we can close this now. Thanks for the hint, @Fernerkundung.

**Comment by dncpax** [comment]
Hi there. Sorry to say, but I encountered this exact error yesterday with v 0.13 on windows 10, using python 3.7.
I was cycling through a few images to download and at the start of a search it crashed:
```
Downloading: 100%|███████████████████████████████████████████████████████████████████| 132M/132M [02:29<00:00, 881kB/s]
Traceback (most recent call last):
  File "C:\OSGeo4W\apps\Python37\lib\site-packages\sentinelsat\sentinel.py", line 1013, in _check_scihub_response
    msg = response.json()['error']['message']['value']
  File "C:\OSGeo4W\apps\Python37\lib\site-packages\requests\models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\OSGeo4W\apps\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\OSGeo4W\apps\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\OSGeo4W\apps\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sentinelsat_band.py", line 109, in <module>
    api._download(band_url, local_filename, api_session, band_contentlength)
  File "C:\OSGeo4W\apps\Python37\lib\site-packages\sentinelsat\sentinel.py", line 822, in _download
    _check_scihub_response(r, test_json=False)
  File "C:\OSGeo4W\apps\Python37\lib\site-packages\sentinelsat\sentinel.py", line 1015, in _check_scihub_response
    if not response.text.strip().startswith('{'):
  File "C:\OSGeo4W\apps\Python37\lib\site-packages\requests\models.py", line 860, in text
    content = str(self.content, encoding, errors='replace')
MemoryError
```

**Comment by dncpax** [comment]
So the logic on my script and where it crashed:
1 - search
2 - loop products
3 - parse response from #1 
4 - loop bands
4 - build url to download specific band
5 - download band with ap._download

It crashed after downloading a band successfully and trying to parse a new band url:
`band_id = bands["d"]["results"][band_idx]["Id"]`
