### ISSUE TITLE
TypeError in _load_subquery

### ISSUE THREAD

**Issue by welir** [sentinelsat/sentinelsat#181]
Then sentenel result search is none.   Converting to int raised exceprion int(json_feed['opensearch:totalResults'])

```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.3\helpers\pydev\pydevd.py", line 1599, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.3\helpers\pydev\pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:/Projects/Python/SantinelDownloader2/downloader.py", line 12, in <module>
    platformname = 'Sentinel-2'
  File "C:\Python27\ArcGIS10.3\lib\site-packages\sentinelsat\sentinel.py", line 135, in query
    response, count = self._load_query(query, formatted_order_by, limit, offset)
  File "C:\Python27\ArcGIS10.3\lib\site-packages\sentinelsat\sentinel.py", line 249, in _load_query
    products, count = self._load_subquery(query, order_by, limit, offset)
  File "C:\Python27\ArcGIS10.3\lib\site-packages\sentinelsat\sentinel.py", line 287, in _load_subquery
    total_results = int(json_feed['opensearch:totalResults'])
TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Comment by welir** [comment]
My solution:
  if ((json_feed['opensearch:totalResults'])) is not None:
                total_results = int(json_feed['opensearch:totalResults'])
            else:
                total_results = 0

**Comment by valgur** [comment]
What version of sentinelsat are you using? The check you are suggesting should already be [included in the code](https://github.com/sentinelsat/sentinelsat/blob/master/sentinelsat/sentinel.py#L275).

**Comment by j08lue** [comment]
We have not yet increased the version number since that fix came in. So you you need to `pip uninstall sentinelsat && pip install https://github.com/sentinelsat/sentinelsat/archive/master.zip` if you want to update. Then you get a nice `SentinelAPIError` instead.

**Comment by welir** [comment]
valgur, Im using version 0.12.1 from python rep

**Comment by welir** [comment]
j08lue, Thanks. Its solution.
