### ISSUE TITLE
Troubles with redirections on s5phub.copernicus.eu

### ISSUE THREAD

**Issue by PhML** [sentinelsat/sentinelsat#258]
A colleague try to test the `s5phub` service available at `https://s5phub.copernicus.eu` with the following request:

```python
import logging
from sentinelsat import SentinelAPI

# Wee need to do the following to catch urllib logs from sentinelsat
ROOT_LOGGER = logging.getLogger()
ROOT_LOGGER.setLevel(logging.DEBUG)

FORMATTER = logging.Formatter("%(asctime)s :: %(name)s :: %(levelname)s :: %(message)s")
STREAM_HANDLER = logging.StreamHandler()
STREAM_HANDLER.setLevel(logging.DEBUG)
STREAM_HANDLER.setFormatter(FORMATTER)

ROOT_LOGGER.addHandler(STREAM_HANDLER)

api = SentinelAPI("s5pguest", "s5pguest", "https://s5phub.copernicus.eu/")

footprint = (
    "POLYGON ((-120.2900000000000063 39.1499999999999986, "
    "-120.2900000000000063 40.3500000000000014, "
    "-121.8100000000000023 40.3500000000000014, "
    "-121.8100000000000023 39.1499999999999986, "
    "-120.2900000000000063 39.1499999999999986))"
)

dates = ("20181108", "20181109")
query_parameters = {"platformname": "Sentinel-5P", "filename": "*L2__CO*"}
r = api.query(footprint, dates, **query_parameters)

```

This example script gives the following error:
```
2019-02-12 11:10:08,095 :: sentinelsat.SentinelAPI :: DEBUG :: Running query: order_by=None, limit=None, offset=0, query=beginPosition:[2018-11-08T00:00:00Z TO 2018-11-09T00:00:00Z] filename:*L2__CO* platformname:Sentinel-5P footprint:"Intersects(POLYGON ((-120.2900000000000063 39.1499999999999986, -120.2900000000000063 40.3500000000000014, -121.8100000000000023 40.3500000000000014, -121.8100000000000023 39.1499999999999986, -120.2900000000000063 39.1499999999999986)))"
2019-02-12 11:10:08,095 :: sentinelsat.SentinelAPI :: DEBUG :: Sub-query: offset=0, limit=None
2019-02-12 11:10:08,096 :: urllib3.connectionpool :: DEBUG :: Starting new HTTPS connection (1): s5phub.copernicus.eu:443
2019-02-12 11:10:08,570 :: urllib3.connectionpool :: DEBUG :: https://s5phub.copernicus.eu:443 "POST /search?format=json&rows=100&start=0 HTTP/1.1" 302 0
2019-02-12 11:10:08,678 :: urllib3.connectionpool :: DEBUG :: Resetting dropped connection: s5phub.copernicus.eu
2019-02-12 11:10:09,046 :: urllib3.connectionpool :: DEBUG :: https://s5phub.copernicus.eu:443 "GET /dhus/search?format=json&rows=100&start=0 HTTP/1.1" 400 None
Traceback (most recent call last):
  File "test.py", line 27, in <module>
    r = api.query(footprint, dates, **query_parameters)
  File "/home/phml/.cache/pypoetry/virtualenvs/scihub/local/lib/python2.7/site-packages/sentinelsat/sentinel.py", line 134, in query
    response, count = self._load_query(query, formatted_order_by, limit, offset)
  File "/home/phml/.cache/pypoetry/virtualenvs/scihub/local/lib/python2.7/site-packages/sentinelsat/sentinel.py", line 242, in _load_query
    products, count = self._load_subquery(query, order_by, limit, offset)
  File "/home/phml/.cache/pypoetry/virtualenvs/scihub/local/lib/python2.7/site-packages/sentinelsat/sentinel.py", line 272, in _load_subquery
    _check_scihub_response(response)
  File "/home/phml/.cache/pypoetry/virtualenvs/scihub/local/lib/python2.7/site-packages/sentinelsat/sentinel.py", line 890, in _check_scihub_response
    raise api_error
sentinelsat.sentinel.SentinelAPIError: HTTP status 400 Bad Request: 
# HTTP Status 400 - Required String parameter 'q' is not present

 **type** Status report

 **message** _Required String parameter 'q' is not present_

 **description** _The request sent by the client was syntactically incorrect._

* * *

### Apache Tomcat/8.0.36

```

The server doesn't receive the parameters. We can see from `urllib` logs that the request is redirected (Code 302 response), not with a `POST` but as a `GET` method. I think the body of the `POST` request  which contains the parameters is lost by this redirection thus leading to the above error.

A solution would be to use a `GET` method instead of a `POST` one so that the redirection wouldn't matter but I think that I has been changed in the past for large query concerns (#36).

The other solution is to ask to `s5phub` to keep the `POST` body when they do the redirection but I don't now if the would/could do that.

*What do you think about this issue?*

**Comment by valgur** [comment]
The redirect can be simply avoided by using the correct base URL (https://s5phub.copernicus.eu/dhus/) directly.
The change in the method from `POST` to `GET` appears to be a somewhat standard behavior for status code 302 handling and is also allowed by the relevant RFC specification. This should be handled better on the server side by using a more appropriate status code, such as `308 Permanent Redirect` which does not allow the method to change.

Unfortunately, I do not see any way of handling this case more elegantly in `sentinelsat` than disabling all redirects altogether by setting `allow_redirects=False` in `requests`. It seems to me that this could cause more issues than solve them, since this looks like an uncommon issue and there might be need for redirects in some cases, such as redirecting from HTTP to HTTPS. So I'm leaning towards keeping it as it is right now.

**Comment by PhML** [comment]
@valgur :roll_eyes: I should have thought about providing the direct link… Indeed it works.
I think the issue can be close then.

**Comment by Fernerkundung** [comment]
Closing at request of OP.
