### ISSUE TITLE
SentinelAPI query Timout when running from script, but same script in jupyter runs fine.

### ISSUE THREAD

**Issue by oyssko** [sentinelsat/sentinelsat#280]
Hey! 

I used the sentinelApi for locating overlaps, and it works great when I'm using it in a jupyter notebook, but fails when I convert it to script. The connection times out. Here is the traceback:
```
Traceback (most recent call last):
  File "SIT_search_script.py", line 24, in <module>
    kept_prods = S2SearchSITPixels(path, username, password, name='navgem')
  File "C:\Users\oyste\OneDrive\Shared\UiT skole\MastersFolder\raster_code\SITProjectUtils.py", line 161, in S2SearchSITPixels
    producttype="S2MSI1C")
  File "C:\Users\oyste\Miniconda3\envs\rasterPy\lib\site-packages\sentinelsat\sentinel.py", line 134, in query
    response, count = self._load_query(query, formatted_order_by, limit, offset)
  File "C:\Users\oyste\Miniconda3\envs\rasterPy\lib\site-packages\sentinelsat\sentinel.py", line 242, in _load_query
    products, count = self._load_subquery(query, order_by, limit, offset)
  File "C:\Users\oyste\Miniconda3\envs\rasterPy\lib\site-packages\sentinelsat\sentinel.py", line 272, in _load_subquery
    _check_scihub_response(response)
  File "C:\Users\oyste\Miniconda3\envs\rasterPy\lib\site-packages\sentinelsat\sentinel.py", line 890, in _check_scihub_response
    raise api_error
sentinelsat.sentinel.SentinelAPIError: HTTP status 500 Internal Server Error: SolrServerException : Timeout occured while waiting response from server at: http://172.30.246.70:8983/solr/dhus
```

And here is the specific query, I don't think I made the .geojson file too big as it worked fine in Jupyter.
```
Sentinel2api = SentinelAPI(user, password)

 print("Searching for Sentinel-2 level 1 products within specified time...")

 S2products1C = Sentinel2api.query(geojson_to_wkt(geom),
                                      date=(starttime, endtime),
                                      platformname='Sentinel-2',
                                      cloudcoverpercentage=cloudcover,
                                      producttype="S2MSI1C")
```

**Comment by Fernerkundung** [comment]
Have you tried it at the same time with Jupyter and as a script or on different days? Scihub can be quite instable on some days.

If you can reproduce them to fail at the same time please also include the `geom`, `starttime` and `endtime.`

**Comment by oyssko** [comment]
I figured it out! But the solution involved having the function with the query in the same script I'm running. Previously I had it in another .py file. Is there a specific reason for this? The geom is around 6kb .geojson file that I've checked several times with different orginal rasters (original, meaning the raster I'm checking for overlap with S2 products), startime is a datetime object that's an hour before the original raster and endtime is an hour after.

**Comment by oyssko** [comment]
I figured it out! But the solution involved having the function with the query in the same script I'm running. Previously I had it in another .py file. Is there a specific reason for this? The geom is around 6kb .geojson file that I've checked several times with different orginal rasters (original, meaning the raster I'm checking for overlap with S2 products), startime is a datetime object that's an hour before the original raster and endtime is an hour after.

**Comment by oyssko** [comment]
I figured it out! But the solution involved having the function with the query in the same script I'm running. Previously I had it in another .py file. Is there a specific reason for this? The geom is around 6kb .geojson file that I've checked several times with different orginal rasters (original, meaning the raster I'm checking for overlap with S2 products), startime is a datetime object that's an hour before the original raster and endtime is an hour after.

**Comment by oyssko** [comment]
I figured it out! But the solution involved having the function with the query in the same script I'm running. Previously I had it in another .py file. Is there a specific reason for this? The geom is around 6kb .geojson file that I've checked several times with different orginal rasters (original, meaning the raster I'm checking for overlap with S2 products), startime is a datetime object that's an hour before the original raster and endtime is an hour after.

**Comment by oyssko** [comment]
I figured it out! But the solution involved having the function with the query in the same script I'm running. Previously I had it in another .py file. Is there a specific reason for this? The geom is around 6kb .geojson file that I've checked several times with different orginal rasters (original, meaning the raster I'm checking for overlap with S2 products), startime is a datetime object that's an hour before the original raster and endtime is an hour after.

**Comment by oyssko** [comment]
> Have you tried it at the same time with Jupyter and as a script or on different days? Scihub can be quite instable on some days.
> 
> If you can reproduce them to fail at the same time please also include the `geom`, `starttime` and `endtime.`

I figured it out! But the solution involved having the function with the query in the same script I'm running. Previously I had it in another .py file. Is there a specific reason for this? The geom is around 6kb .geojson file that I've checked several times with different orginal rasters (original, meaning the raster I'm checking for overlap with S2 products), startime is a datetime object that's an hour before the original raster and endtime is an hour after.
