### ISSUE TITLE
Required String parameter 'q' is not present

### ISSUE THREAD

**Issue by drnextgis** [sentinelsat/sentinelsat#289]
I'm trying to run this simple command but it throws an error:

```
$ sentinelsat -u *** -p *** -g catalunya.geojson --sentinel 2 --cloud 30
Traceback (most recent call last):
  File "/home/denis/satellogic/env-shub/bin/sentinelsat", line 11, in <module>
    sys.exit(cli())
  File "/home/denis/satellogic/env-shub/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/denis/satellogic/env-shub/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/denis/satellogic/env-shub/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/denis/satellogic/env-shub/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/denis/satellogic/env-shub/lib/python3.6/site-packages/sentinelsat/scripts/cli.py", line 160, in cli
    order_by=order_by, limit=limit, **search_kwargs)
  File "/home/denis/satellogic/env-shub/lib/python3.6/site-packages/sentinelsat/sentinel.py", line 147, in query
    response, count = self._load_query(query, formatted_order_by, limit, offset)
  File "/home/denis/satellogic/env-shub/lib/python3.6/site-packages/sentinelsat/sentinel.py", line 272, in _load_query
    products, count = self._load_subquery(query, order_by, limit, offset)
  File "/home/denis/satellogic/env-shub/lib/python3.6/site-packages/sentinelsat/sentinel.py", line 304, in _load_subquery
    _check_scihub_response(response)
  File "/home/denis/satellogic/env-shub/lib/python3.6/site-packages/sentinelsat/sentinel.py", line 1027, in _check_scihub_response
    raise api_error
sentinelsat.sentinel.SentinelAPIError: HTTP status 400 Bad Request: 
# HTTP Status 400 - Required String parameter 'q' is not present

 **type** Status report

 **message** _Required String parameter 'q' is not present_

 **description** _The request sent by the client was syntactically incorrect._

* * *

### Apache Tomcat/8.0.36
```

**Comment by drnextgis** [comment]
Sometimes for the same request I get the following error:

```
$ sentinelsat -u *** -p *** -g catalunya.geojson --sentinel 2 --cloud 30
Traceback (most recent call last):
  File "/home/denis/satellogic/env-shub/lib/python3.6/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/home/denis/satellogic/env-shub/lib/python3.6/site-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.6/ssl.py", line 975, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.6/ssl.py", line 944, in send
    return self._sslobj.write(data)
  File "/usr/lib/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denis/satellogic/env-shub/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/denis/satellogic/env-shub/lib/python3.6/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/denis/satellogic/env-shub/lib/python3.6/site-packages/urllib3/util/retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/denis/satellogic/env-shub/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/denis/satellogic/env-shub/lib/python3.6/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/home/denis/satellogic/env-shub/lib/python3.6/site-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.6/ssl.py", line 975, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.6/ssl.py", line 944, in send
    return self._sslobj.write(data)
  File "/usr/lib/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denis/satellogic/env-shub/bin/sentinelsat", line 11, in <module>
    sys.exit(cli())
  File "/home/denis/satellogic/env-shub/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/denis/satellogic/env-shub/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/denis/satellogic/env-shub/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/denis/satellogic/env-shub/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/denis/satellogic/env-shub/lib/python3.6/site-packages/sentinelsat/scripts/cli.py", line 160, in cli
    order_by=order_by, limit=limit, **search_kwargs)
  File "/home/denis/satellogic/env-shub/lib/python3.6/site-packages/sentinelsat/sentinel.py", line 147, in query
    response, count = self._load_query(query, formatted_order_by, limit, offset)
  File "/home/denis/satellogic/env-shub/lib/python3.6/site-packages/sentinelsat/sentinel.py", line 272, in _load_query
    products, count = self._load_subquery(query, order_by, limit, offset)
  File "/home/denis/satellogic/env-shub/lib/python3.6/site-packages/sentinelsat/sentinel.py", line 303, in _load_subquery
    timeout=self.timeout)
  File "/home/denis/satellogic/env-shub/lib/python3.6/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/denis/satellogic/env-shub/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/denis/satellogic/env-shub/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/denis/satellogic/env-shub/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))
```

**Comment by valgur** [comment]
That's pretty weird. Can you upload the `catalunya.geojson` somewhere? As a [gist](https://gist.github.com/) for example.

**Comment by drnextgis** [comment]
https://gist.github.com/drnextgis/3861f0ef32884df6672621a1ff12b8ac

**Comment by drnextgis** [comment]
If simplify geometry in geojson file it works:

```
$ sentinelsat -u *** -p *** -g catalunyacv.geojson -s 20190401 -e 20190501 --sentinel 2 --cloud 100
Querying products: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 378/378 [00:02<00:00, 127.33 products/s]
Found 378 products
Product 0a01d5ce-5d0b-4fde-ad7c-d6d929ef0937 - Date: 2019-04-30T10:30:31.025Z, Instrument: MSI, Mode: , Satellite: Sentinel-2, Size: 599.16 MB
...
```

**Comment by valgur** [comment]
Thanks!
I suspect the AOI polygon is too detailed for the server to handle. Both error messages sound like the server is confused by a too big request body. As a rule of thumb, the scihub server can handle only around 200 points max before the query becomes too large. 
You can use [api.format_query()](https://sentinelsat.readthedocs.io/en/stable/api.html#sentinelsat.SentinelAPI.format_query) and [api.check_query_length()](https://sentinelsat.readthedocs.io/en/stable/api.html#sentinelsat.SentinelAPI.check_query_length) in the Python API to check that the query is not too long for the server to handle.

Thanks for reporting this. There's some room for improvement here - sentinelsat should probably produce more helpful error messages or warning in such cases and the query AOI complexity limitations should be mentioned somewhere in the docs.

**Comment by drnextgis** [comment]
Thanks for quick reply!

**Comment by Fernerkundung** [comment]
Thanks for the detailed report @drnextgis. This is a bug on the server side. Extending the CLI to raise a warning on complex polygons, as suggested by @valgur, seems to be the best way to handle this.

I created a new issue for this task. (#290)

**Comment by adibratul** [comment]
can anyone help
https://github.com/sentinelsat/sentinelsat/issues/388

**Comment by SkalskiP** [comment]
Is that issue solved? Trying to make query using the API but getting the following error:

```
python -m src.sentinel.query -g data/geo/rotterdam-2.geojson                                               2 ↵
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/piotrskalski/Documents/work/satim/OREC/src/sentinel/query.py", line 28, in <module>
    products = api.query(footprint, limit=2)
  File "/Users/piotrskalski/Documents/work/satim/OREC/venv/lib/python3.8/site-packages/sentinelsat/sentinel.py", line 208, in query
    response, count = self._load_query(query, formatted_order_by, limit, offset)
  File "/Users/piotrskalski/Documents/work/satim/OREC/venv/lib/python3.8/site-packages/sentinelsat/sentinel.py", line 349, in _load_query
    products, count = self._load_subquery(query, order_by, limit, offset)
  File "/Users/piotrskalski/Documents/work/satim/OREC/venv/lib/python3.8/site-packages/sentinelsat/sentinel.py", line 387, in _load_subquery
    _check_scihub_response(response)
  File "/Users/piotrskalski/Documents/work/satim/OREC/venv/lib/python3.8/site-packages/sentinelsat/sentinel.py", line 1320, in _check_scihub_response
    raise api_error
sentinelsat.sentinel.SentinelAPIError: HTTP status 400 Bad Request:
# HTTP Status 400 – Bad Request

* * *

 **Type** Status Report

 **Message** Required String parameter 'q' is not present

 **Description** The server cannot or will not process the request due to
something that is perceived to be a client error (e.g., malformed request
syntax, invalid request message framing, or deceptive request routing).

* * *

### Apache Tomcat/8.0.53
```

This is my code:

```python
api = SentinelAPI(user=None, password=None)
footprint = geojson_to_wkt(read_geojson(spec.geojson_path))
products = api.query(footprint, limit=2)
api.download_all(products)
```

This is geojson I'm using:

```geojson
{
   "type":"FeatureCollection",
   "features":[
      {
         "type":"Feature",
         "properties":{
            
         },
         "geometry":{
            "type":"Polygon",
            "coordinates":[
               [
                  [
                     3.879547119140625,
                     51.89429152246628
                  ],
                  [
                     4.1851043701171875,
                     51.89429152246628
                  ],
                  [
                     4.1851043701171875,
                     52.0400325031185
                  ],
                  [
                     3.879547119140625,
                     52.0400325031185
                  ],
                  [
                     3.879547119140625,
                     51.89429152246628
                  ]
               ]
            ]
         }
      }
   ]
}
```

**Comment by SkalskiP** [comment]
I also tried with less precise geojson:

```
{
   "type":"FeatureCollection",
   "features":[
      {
         "type":"Feature",
         "properties":{

         },
         "geometry":{
            "type":"Polygon",
            "coordinates":[
               [
                  [
                     3.8795,
                     51.8942
                  ],
                  [
                     4.1851,
                     51.8942
                  ],
                  [
                     4.1851,
                     52.0400
                  ],
                  [
                     3.8795,
                     52.0400
                  ],
                  [
                     3.8795,
                     51.8942
                  ]
               ]
            ]
         }
      }
   ]
}
```

`check_query_length()` resulted in `0.034281361097003554`

But I still get the same error. Would be grateful for any help.

**Comment by valgur** [comment]
I'm not sure what's causing that error for you. That code and GeoJSON sample works fine for me. Try using the development version
```bash
pip install git+https://github.com/sentinelsat/sentinelsat.git --upgrade
```
If that does not fix the issue for you, then maybe this currently open PR will: #474.

**Comment by SkalskiP** [comment]
@valgur thank you very much. The Development version works for me. I can query API. Up until now, I was using `0.14` which for some reason raises that error. One more time thank you. When can I expect the next stable release that would eliminate that error?

And also one more question - I'm just looking for advice. What library are you using to crop SAR images? Those downloaded from api are gigantic `.tiff` files. Maybe you would have some pro tip for me? :)

**Comment by valgur** [comment]
> When can I expect the next stable release that would eliminate that error on pypi?

Probably some time next week. You can keep an eye on #434 for more details.

> What library are you using to crop SAR images?

The [SNAP toolbox](https://step.esa.int/main/) is probably the best publicly available tool for this. Using [GDAL](https://gis.stackexchange.com/questions/79919/cropping-geotiff-with-gdalwarp) might also work.

**Comment by SkalskiP** [comment]
I was thinking about some python library no desktop app, but still thank you for your response :)

**Comment by CharlesNickmilder** [comment]
Got here due to the same issue, I will try to update the lib

@SkalskiP I saw your question about the SAR images manipulation. Have you looked at the command line interface for SNAP (gpt ...) ? One use case is detailled in https://doi.org/10.3390/ECRS-3-06201
