### ISSUE TITLE
cannot download using geojson file with sentinelsat command

### ISSUE THREAD

**Issue by elnazzz1** [sentinelsat/sentinelsat#307]
Hi

I just tried to focus the satellite download data command on a polygon in geojson and have had trouble
getting past the following error message:

------------------------------------------------------------------------------------------
```
 sentinelsat -u *** -p *** -g coalingua.geojson --sentinel 2 -d
```

```
Traceback (most recent call last):
  File "/home/elnazz_akbari/.local/bin/sentinelsat", line 11, in <module>
    sys.exit(cli())
  File "/home/elnazz_akbari/.local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/elnazz_akbari/.local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/elnazz_akbari/.local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/elnazz_akbari/.local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/elnazz_akbari/.local/lib/python2.7/site-packages/sentinelsat/scripts/cli.py", line 160, in cli
    order_by=order_by, limit=limit, **search_kwargs)
  File "/home/elnazz_akbari/.local/lib/python2.7/site-packages/sentinelsat/sentinel.py", line 147, in query
    response, count = self._load_query(query, formatted_order_by, limit, offset)
  File "/home/elnazz_akbari/.local/lib/python2.7/site-packages/sentinelsat/sentinel.py", line 272, in _load_query
    products, count = self._load_subquery(query, order_by, limit, offset)
  File "/home/elnazz_akbari/.local/lib/python2.7/site-packages/sentinelsat/sentinel.py", line 316, in _load_subquery
    'Invalid query string. Check the parameters and format.', response)
sentinelsat.sentinel.SentinelAPIError: HTTP status 200 OK: Invalid query string. Check the parameters and format.
```
------------------------------------------------------------------------------------------

here is my coalingua.geojson file:
```
{
  "type": "Feature",
  "properties": {
    "name": "California",
    "area": 1150180
  },
  "geometry": {
    "type": "Polygon",
    "coordinates": [
      [
        [
          -120.151119,
          36.119414
        ],
        [
          -120.146673,
          36.122999
        ],
        [
          -120.146788,
          36.123042
        ],
        [
          -120.155604,
          36.123039
        ],
        [
          -120.155594,
          36.115997
        ],
        [
          -120.155344,
          36.116121
        ],
        [
          -120.155348,
          36.115785
        ],
	[
          -120.146621,
          36.115789
        ],
        [
          -120.146673,
          36.122999
        ],
        [
          -120.151119,
          36.119414
        ]
      ]
    ]
  }
}
```

**Comment by Fernerkundung** [comment]
Your polygon has a self-intersection and is an invalid geometry. If you fix it the search works. Keep in mind that `sentinelsat` will only query products published in the last 24 hours unless you give it a `--start` and `--end` date.

```
{
      "type": "Feature",
      "properties": {
        "name": "California",
        "area": 1150180
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -120.15562534332274,
              36.115785518251045
            ],
            [
              -120.1466131210327,
              36.115785518251045
            ],
            [
              -120.1466131210327,
              36.12305683573126
            ],
            [
              -120.15562534332274,
              36.12305683573126
            ],
            [
              -120.15562534332274,
              36.115785518251045
            ]
          ]
        ]
      }
    }
```
