### ISSUE TITLE
Long term archive (LTA) Exception in thread Thread-2:

### ISSUE THREAD

**Issue by dpabon** [sentinelsat/sentinelsat#328]
Hi everyone, I'm trying to download some products from the LTA. When I run the program produced the following error:
```
Found 186 products
Will download 186 products using 2 workers
Product f5905042-44e7-49c2-be79-4463c5ea4ed4 is in LTA.
Product 56f6a24e-7c5e-49d6-b118-b0c493385253 is in LTA.
Product 1d685a19-9280-423f-833b-268a56d4c7c1 is in LTA.
Product 4cf226e1-dfb2-4dad-9ef6-4e13db20be18 is in LTA.
Product ac248ae6-06cb-4910-b85a-af22b34f3519 is in LTA.
Product d44c79a6-cf5c-4ad8-ac92-803eabfff0ad is in LTA.
Product 91e83079-ceaa-4eba-9d54-b1b266c88806 is in LTA.
Product 56ab6d2d-f5e8-4ee2-b33d-2f99a28d24f0 is in LTA.
Product 4ddc2313-9a4e-4905-928f-4e7d98153efd is in LTA.
Product 49f1a962-e8d1-4f8e-a438-4a7c3f1db01b is in LTA.
Product 6fbb2a89-fd4d-4803-bc0e-60401f9ff81f is in LTA.
Product 8a9e392f-1a7a-4131-a177-d58a6834252e is in LTA.
Product 07ac6e7c-95bd-4b49-bf80-4bc38a6b8a34 is in LTA.
Product 2131b38f-e4b0-4d09-a24e-2fd9b1807edb is in LTA.
Product 776faaef-c7c6-4239-8583-1fb36a4b1a68 is in LTA.
Product e0e56446-94d9-4cea-bbf9-a63091e7d58c is in LTA.
Product 7bc23a52-0132-4e8d-9af8-3e12dcb09ad7 is in LTA.
Product b26198f2-cba6-40ec-9358-f33a0b8a558f is in LTA.
Product a39d022d-b587-4438-99d3-87fbbb67affa is in LTA.
Product 77346c58-2980-4db5-9e75-07189632076a is in LTA.
Product e970f549-42ca-491c-86cf-f14c7f7a5f3b is in LTA.
Product abdc9b29-edd0-4db9-a00c-b55f48fd7fab is in LTA.
Product ad42f32a-a741-4f4f-827a-a802d28c1271 is in LTA.
Product d12d43e9-51b0-49cf-88bf-41047fa8ee01 is in LTA.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/User/homes/dpabon/.local/lib/python2.7/site-packages/sentinelsat/sentinel.py", line 796, in _trigger_offline_retrieval_until_stop
    status_code = self._trigger_offline_retrieval(product_info["url"])
  File "/User/homes/dpabon/.local/lib/python2.7/site-packages/sentinelsat/sentinel.py", line 619, in _trigger_offline_retrieval
    with self.session.get(url, auth=self.session.auth, timeout=self.timeout) as r:
Attribute error: __exit__
```
OS: Ubuntu server 16.04

Thanks in advance for your help.

**Comment by j08lue** [comment]
So the return of `self.session.get` is not a context manager. Maybe you are using a really old version of `requests`? The PR that fixed this was merged in 2017 https://github.com/psf/requests/pull/4137

Try `pip install --upgrade requests` and then run that code again.

**Comment by dpabon** [comment]
I updated the module. 
```
python -c "import requests; print(requests.__version__)"
2.22.0
```
however, it produces the same error.

**Comment by j08lue** [comment]
Weird. Are you sure you installed requests the same place as sentinelsat? Sentinelsat seems to live in some old Python 2 environment you have there. Maybe use a fresh venv and try things there? Something like

```
python3 -m venv ~/.venv/sentinelsat
source ~/.venv/sentinelsat/bin/activate
pip install -U pip
pip install sentinelsat
python -c "import sentinelsat; print(sentinelsat.__file__)"
python -c "import requests; print(requests.__version__)"
python -c "import requests; print(requests.__file__)"
```

**Comment by dpabon** [comment]
Thanks!! I create a new environment using conda and now it's working well.
