### ISSUE TITLE
S5P query fails

### ISSUE THREAD

**Issue by moris626** [sentinelsat/sentinelsat#380]
Impossible to execute query search  on [s5phub portal ](https://s5phub.copernicus.eu/dhus) because the portal doesn't support post requests. 

Replacing session.post with session.get in  _load_subquery() function it works!

It is possible to implement the search as get for sentinel5p?

**Comment by Fernerkundung** [comment]
Can you provide a working example please, maybe as a branch or (WIP) PR?

Is this behaviour documented by SciHub - would be interesting to follow their documentation if they changed something recently.

**Comment by valgur** [comment]
POST could easily be replaced with GET for queries. The only issue it would cause is breaking Unicode support, which could maybe be resolved somehow. Alternatively, we could simply sacrifice Unicode support altogether, which is probably never required really anyway.

**Comment by moris626** [comment]
my branch (works with scihub / coda / s5phub ) available [here](https://github.com/moris626/sentinelsat/tree/moris626-patch-s5phub-coda) 

This is the error with current version:
```
Python 3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sentinelsat import SentinelAPI
>>> api = SentinelAPI('s5pguest','s5pguest','https://s5phub.copernicus.eu')
>>> api.query(producttype='L2__AER_AI')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/moris/test/lib/python3.8/site-packages/sentinelsat/sentinel.py", line 208, in query
    response, count = self._load_query(query, formatted_order_by, limit, offset)
  File "/home/moris/test/lib/python3.8/site-packages/sentinelsat/sentinel.py", line 349, in _load_query
    products, count = self._load_subquery(query, order_by, limit, offset)
  File "/home/moris/test/lib/python3.8/site-packages/sentinelsat/sentinel.py", line 387, in _load_subquery
    _check_scihub_response(response)
  File "/home/moris/test/lib/python3.8/site-packages/sentinelsat/sentinel.py", line 1320, in _check_scihub_response
    raise api_error
sentinelsat.sentinel.SentinelAPIError: HTTP status 400 Bad Request: 
# HTTP Status 400 - Required String parameter 'q' is not present

 **type** Status report

 **message** _Required String parameter 'q' is not present_

 **description** _The request sent by the client was syntactically incorrect._

* * *

### Apache Tomcat/8.0.36

```

and this the output with moris626-patch-s5phub-coda branch

```
Python 3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sentinelsat import SentinelAPI
>>> api = SentinelAPI('s5pguest','s5pguest','https://s5phub.copernicus.eu')
>>> api.query(producttype='L2__AER_AI')
Querying products:   3%|██████▎                                                                                                                                                                                                     | 500/16040 [00:01<01:10, 220.65 products/s]
```
