### ISSUE TITLE
 SentinelAPIError: # HTTP Status 400 - Required String parameter 'q' is not present

### ISSUE THREAD

**Issue by adibratul** [sentinelsat/sentinelsat#388]
I want to download sentine5p data using sentinelsat here is my following code which shows error 

```
from sentinelsat import SentinelAPI, geojson_to_wkt, read_geojson

user= 's5pguest'
password= 's5pguest'

area = r'map.geojson'



api= SentinelAPI(user, password,'http://s5phub.copernicus.eu/dhus')
footprint= geojson_to_wkt(read_geojson(area))

product_2020 = api.query(footprint, date=('20200101','20200101'),
                          producttype = 'L2__NO2___',)

#downloading 
api.download_all(product_2020, directory_path='/home/adib/COVID AIR/Mycode')

```

the error message is 

```

runfile('/home/adib/COVID AIR/Mycode/Download Sentinel5p.py', wdir='/home/adib/COVID AIR/Mycode')
Traceback (most recent call last):

  File "/home/adib/COVID AIR/Mycode/Download Sentinel5p.py", line 23, in <module>
    producttype = 'L2__NO2___')

  File "/home/adib/anaconda3/lib/python3.7/site-packages/sentinelsat/sentinel.py", line 208, in query
    response, count = self._load_query(query, formatted_order_by, limit, offset)

  File "/home/adib/anaconda3/lib/python3.7/site-packages/sentinelsat/sentinel.py", line 349, in _load_query
    products, count = self._load_subquery(query, order_by, limit, offset)

  File "/home/adib/anaconda3/lib/python3.7/site-packages/sentinelsat/sentinel.py", line 387, in _load_subquery
    _check_scihub_response(response)

  File "/home/adib/anaconda3/lib/python3.7/site-packages/sentinelsat/sentinel.py", line 1320, in _check_scihub_response
    raise api_error

SentinelAPIError: # HTTP Status 400 - Required String parameter 'q' is not present

 **type** Status report

 **message** _Required String parameter 'q' is not present_

 **description** _The request sent by the client was syntactically incorrect._

* * *

### Apache Tomcat/8.0.36`
```

**Comment by valgur** [comment]
Try
```python
query = self.format_query(footprint, date=('20200101','20200101'), producttype = 'L2__NO2___',)
print("Query string length is {} times the max allowed length".format(api.check_query_length(query))
```
If the the query string size is too big, you will have to simplify the GeoJSON feature to contain be less than ~200 vertices.
