### ISSUE TITLE
API error when querying codarep.eumetsat.int

### ISSUE THREAD

**Issue by OGraffeuille** [sentinelsat/sentinelsat#398]
Hi there,

I need to download Sentinel-3 OLCI sensor data that's over a year old. From my understanding this means I need to query https://codarep.eumetsat.int/. 
[Source 1](https://www.eumetsat.int/website/home/Data/DataDelivery/CopernicusOnlineDataAccess/index.html)
[Source 2](https://github.com/sentinelsat/sentinelsat/issues/234)

My issue is that I get an API error when querying https://codarep.eumetsat.int/. This error occurs with both the python API and the commandline interface. However, querying https://coda.eumetsat.int/ returns products I expect.

Python API:
```
from sentinelsat import SentinelAPI, read_geojson, geojson_to_wkt
from datetime import date

api = SentinelAPI('*****', '*****', api_url='https://codarep.eumetsat.int/')
footprint = geojson_to_wkt(read_geojson("file.geojson"))
products = api.query(footprint, producttype="OL_1_EFR___")
print(products)
```

```
Traceback (most recent call last):

  File "C:\Users\*****\Documents\PhD\Data\Remote sensing\Sentinelsat\untitled0.py", line 14, in <module>
    products = api.query(footprint, producttype="OL_1_EFR___")

  File "C:\Users\*****\anaconda3\lib\site-packages\sentinelsat\sentinel.py", line 208, in query
    response, count = self._load_query(query, formatted_order_by, limit, offset)

  File "C:\Users\*****\anaconda3\lib\site-packages\sentinelsat\sentinel.py", line 349, in _load_query
    products, count = self._load_subquery(query, order_by, limit, offset)

  File "C:\Users\*****\anaconda3\lib\site-packages\sentinelsat\sentinel.py", line 387, in _load_subquery
    _check_scihub_response(response)

  File "C:\Users\*****\anaconda3\lib\site-packages\sentinelsat\sentinel.py", line 1320, in _check_scihub_response
    raise api_error

SentinelAPIError
```

Commandline:
```
C:\*****\Data\Remote sensing\Sentinelsat\geojson>sentinelsat --url https://codarep.eumetsat.int/ -u ***** -p ***** -g file.geojson
```

```
Traceback (most recent call last):
  File "c:\users\*****\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\*****\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\*****\anaconda3\Scripts\sentinelsat.exe\__main__.py", line 7, in <module>
  File "c:\users\*****\anaconda3\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\*****\anaconda3\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\*****\anaconda3\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\*****\anaconda3\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\*****\anaconda3\lib\site-packages\sentinelsat\scripts\cli.py", line 220, in cli
    products = api.query(date=(start, end), order_by=order_by, limit=limit, **search_kwargs)
  File "c:\users\*****\anaconda3\lib\site-packages\sentinelsat\sentinel.py", line 208, in query
    response, count = self._load_query(query, formatted_order_by, limit, offset)
  File "c:\users\*****\anaconda3\lib\site-packages\sentinelsat\sentinel.py", line 349, in _load_query
    products, count = self._load_subquery(query, order_by, limit, offset)
  File "c:\users\*****\anaconda3\lib\site-packages\sentinelsat\sentinel.py", line 387, in _load_subquery
    _check_scihub_response(response)
  File "c:\users\*****\anaconda3\lib\site-packages\sentinelsat\sentinel.py", line 1320, in _check_scihub_response
    raise api_error
sentinelsat.sentinel.SentinelAPIError: HTTP status 200 OK:
```

Thank you very much for this useful and well set out library.
Cheers, Oli

**Comment by OGraffeuille** [comment]
Cheers for the reply Fernerkundung,

Unfortunately I don't think this is the reason for the error I'm facing. I removed date filters from my above example to make it as simple as possible, but the same error occurs with dates, eg:
```
C:\*****\Data\Remote sensing\Sentinelsat\geojson>sentinelsat --url https://codarep.eumetsat.int/ -u ***** -p ***** -g file.geojson  **-s 20000101 -e 20200820**
```
Gives the same error as the OP. I also doubt that this error is occurring because my problem is not that there are no results, it's that there's an error when I query the codarep URL. Have you seen an APIError like this before?

**Comment by geom16011** [comment]
I have a similar issue 

I want to find images Sentinel 3 images (OL_2_WRR___) from eumetsat and i get the following error: 

products = api.query(footprint, date=('20160823', '20160824'), producttype='OL_2_WRR___')
Traceback (most recent call last):
  File "<pyshell#10>", line 1, in <module>
    products = api.query(footprint, date=('20160823', '20160824'), producttype='OL_2_WRR___')
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\sentinelsat\sentinel.py", line 144, in query
    raise e
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\sentinelsat\sentinel.py", line 135, in query
    response, count = self._load_query(query, formatted_order_by, limit, offset)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\sentinelsat\sentinel.py", line 249, in _load_query
    products, count = self._load_subquery(query, order_by, limit, offset)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\sentinelsat\sentinel.py", line 279, in _load_subquery
    _check_scihub_response(response)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\sentinelsat\sentinel.py", line 889, in _check_scihub_response
    raise api_error
sentinelsat.sentinel.SentinelAPIError: HTTP status 200 OK: 

Any ideas? Did anybody solve the problem?

**Comment by felipems11** [comment]
Hello guys. 
I had a look into it and I believe there is an issue regarding the format of the server's response. 
The server 'https://codarep.eumetsat.int' does not respond anything if we choose the json format. But it works fine for the other formats (please check the image below). 

Do you think it would be interesting to consider working on the xml output?


Here are some links I tested:
https://codarep.eumetsat.int/search?q=platformname:Sentinel-3%20producttype:OL_2_WRR___&format=xml

https://codarep.eumetsat.int/search?q=platformname:Sentinel-3%20producttype:OL_2_WRR___&format=atom

https://codarep.eumetsat.int/search?q=platformname:Sentinel-3%20producttype:OL_2_WRR___&format=application/metalink4%2Bxml

https://codarep.eumetsat.int/search?q=platformname:Sentinel-3%20producttype:OL_2_WRR___&format=json


I hope this helps at least for a discussion. This is my first collaboration here and my first contact with this project. 

Best regards!



![image](https://user-images.githubusercontent.com/24700128/93731096-ee078c80-fba1-11ea-9e40-b6baa5e230ed.png)

**Comment by Fernerkundung** [comment]
Switching all of the logic in `sentinelsat` to work with XML is a huge refactoring effor. Have you contacted the CODA helpdesk why they deactivated the JSON response which is included in any other standard DHuS instance?

**Comment by felipems11** [comment]
Hi Fernerkundung. I just wrote to the helpdesk about this issue. I will post the answer here as soon as I get it.
Regards.

**Comment by felipems11** [comment]
I just got an answer: They are aware of the issue and working on its solution. No deadline provided.

**Comment by Fernerkundung** [comment]
Ok - feel free to comment on this so we can reopen it if there are still issues with coda after they resolved the JSON issue.
