### ISSUE TITLE
Sentinelsat download_all doesn't works with LTA

### ISSUE THREAD

**Issue by ervingrebesh** [sentinelsat/sentinelsat#428]
Hello, 
I'm trying to run download_all, but have found that this functions doesn't supports LTA data retrieving, however by descriptions it does.  Cases #427  and #425 describes same functionality problem. I hope we could get some changes in code. 

I have  tested both `/apihub` as well as ` /dhus`

```
# connect to the API
api = SentinelAPI(u, p, 'https://scihub.copernicus.eu/apihub')

tiles = ['34VDJ']
query_kwargs = {
    'platformname': 'Sentinel-2',
    'producttype': 'S2MSI1C',
    'date': ('20180112', '20180122')}
products = OrderedDict()
for tile in tiles:
    kw = query_kwargs.copy()
    kw['tileid'] = tile
    pp = api.query(**kw)
    products.update(pp)

# go to df list
products_df = api.to_dataframe(products)

# ask for data
api.download_all(products_df.index, directory_path = '/mnt/e64bce92-a926-422d-9093-0c5457ce19f3/SAT_archiv/34VDJ/PRODUCT/' ,  max_attempts=20, lta_retry_delay=900)


```

**Error result:**

```
>>> api.download_all(products_df.index, directory_path = '/mnt/e64bce92-a926-422d-9093-0c5457ce19f3/SAT_archiv/34VDJ/PRODUCT/' ,  max_attempts=20, lta_retry_delay=900)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lakmakaka/.local/lib/python2.7/site-packages/sentinelsat/sentinel.py", line 779, in download_all
    if not dl_task.exception() and dl_task.result():
  File "/home/lakmakaka/.local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 516, in exception
    return self.exception_info(timeout)[0]
  File "/home/lakmakaka/.local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 486, in exception_info
    raise CancelledError()
concurrent.futures._base.CancelledError
```

The same error if I try: 
```
# connect to the API
api = SentinelAPI(u, p, 'https://scihub.copernicus.eu/dhus')
```

The problem is only with files that are in LTA. If we try some online dataset, like: 

```
tiles = ['34VDJ']
query_kwargs = {
    'platformname': 'Sentinel-2',
    'producttype': 'S2MSI1C',
    'date': ('20200112', '20200122')}
products = OrderedDict()
for tile in tiles:
    kw = query_kwargs.copy()
    kw['tileid'] = tile
    pp = api.query(**kw)
    products.update(pp)
```
Using both `/apihub` or `/dhus` it works. 

Maybe someone could inspect where is problem? 
Previously I used dhus service with sliding order to get LTA files, and seems download_all functionality should complete all tasks if it will works. Does it worked previously with LTA files?

**Comment by j08lue** [comment]
LTA triggering and download used to work ok-ish, but you are now the second to run into this issue. Please see #425, I am closing this as duplicate.
