### ISSUE TITLE
Authorization Error 401 status code.

### ISSUE THREAD

**Issue by Kay0777** [sentinelsat/sentinelsat#446]
Dear, Welle

When Using this module I mean SentinelAPI gives me an error like this.
After that, I checked my post on the requests module with added cookies from giving the postman.
The post is giving a response with status 200 and I can get results.
So, Please check this!!!
Thanks.

**Comment by zi-dan** [comment]
From yesterday evening I got the same problem. Before that everything works OK. The full tracestack looks like below

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/sentinelsat/sentinel.py", line 147, in query
    response, count = self._load_query(query, formatted_order_by, limit, offset)
  File "/opt/conda/lib/python3.6/site-packages/sentinelsat/sentinel.py", line 272, in _load_query
    products, count = self._load_subquery(query, order_by, limit, offset)
  File "/opt/conda/lib/python3.6/site-packages/sentinelsat/sentinel.py", line 304, in _load_subquery
    _check_scihub_response(response)
  File "/opt/conda/lib/python3.6/site-packages/sentinelsat/sentinel.py", line 1027, in _check_scihub_response
    raise api_error
sentinelsat.sentinel.SentinelAPIError: HTTP status 401 Unauthorized: 
# HTTP Status 401 – Unauthorized
* * *
 **Type** Status Report
 **Message** Unauthorized
 **Description** The request has not been applied because it lacks valid
authentication credentials for the target resource.
* * *
### Apache Tomcat/8.0.53

**Comment by EmanuelCastanho** [comment]
#444 The API url was updated.
