### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split' when downloading from CODA

### ISSUE THREAD

**Issue by ojaace** [sentinelsat/sentinelsat#494]
I am unsure of what is going on here. Trying to download a product, using its uuid, from https://coda.eumetsat.int.

Using the following CLI command:
`sentinelsat --uuid 79932d70-5c22-413c-9e29-493f53bc5c2d --download`

Using `sentinelsat, version 1.0.1`

I have downloaded from CODA before, so I'm a bit confused. I guess CODA is not responding with the filename in the same way anymore?

```
Found 1 products                                                                                                                                                                              
Will download 1 products using 2 workers                                                                                                                                                      
Fetching archival status: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.25 products/s]
79932d70-5c22-413c-9e29-493f53bc5c2d is online. Starting download                                                                                                                             
There was an error downloading S3B_OL_2_WFR____20210605T091935_20210605T092235_20210605T113051_0179_053_150_1980_MAR_O_NR_003                                                                 
Traceback (most recent call last):                                                                                                                                                            
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/dhus-test-NW2MfJEz-py3.8/lib/python3.8/site-packages/sentinelsat/sentinel.py", line 890, in _download_online_retry                           
    return self.download(id, directory_path, checksum, **kwargs)                                                                                                                              
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/dhus-test-NW2MfJEz-py3.8/lib/python3.8/site-packages/sentinelsat/products.py", line 178, in download                                         
    return sentinelsat.SentinelAPI.download(self, id, directory_path, checksum, **kwargs)                                                                                                     
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/dhus-test-NW2MfJEz-py3.8/lib/python3.8/site-packages/sentinelsat/sentinel.py", line 511, in download                                         
    filename = self._get_filename(product_info)                                                                                                                                               
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/dhus-test-NW2MfJEz-py3.8/lib/python3.8/site-packages/sentinelsat/sentinel.py", line 590, in _get_filename                                    
    filename = cd.split("=", 1)[1].strip('"')                                                                                                                                                 
AttributeError: 'NoneType' object has no attribute 'split'                                                                                                                                    
9 retries left
```

**Comment by ojaace** [comment]
I do not think I have the time to learn how to do something like that right now. I am more of a user, even though I'm very much interested in becoming more of a contributor of various projects in the future!

**Comment by rbrishabh** [comment]
Hi! I can try to help!

**Comment by wavic** [comment]
I had the  same error. Just putted in a condition

`if check_cursor_global(lines, "inherits="):
            cursor_theme = check_cursor_global(lines, "Inherits=").split("=")[1]`
