### ISSUE TITLE
500 Internal Server Error using api.download_all() 

### ISSUE THREAD

**Issue by SteffanDavies** [sentinelsat/sentinelsat#514]
After reading the docs and issues here, api.download_all() is supposed to retrieve offline products by queuing them. But I get an error...

Error:
```Powershell
Fetching archival status:   0%|                                                                                                                                | 0/62 [00:01<?, ? products/s]
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\sentinelsat\sentinel.py", line 1433, in _check_scihub_response
    response.raise_for_status()
  File "C:\Users\steff\AppData\Roaming\Python\Python39\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://apihub.copernicus.eu/apihub/odata/v1/Products('acb14b3d-3111-413d-a244-661195bf9d89')/$value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\steff\OneDrive\Documentos\change_detection_a24_2019_2020_s2\test.py", line 11, in <module>
    api.download_all(products)
  File "C:\Python39\lib\site-packages\sentinelsat\sentinel.py", line 723, in download_all
    is_online = not self.trigger_offline_retrieval(pid)
  File "C:\Python39\lib\site-packages\sentinelsat\sentinel.py", line 645, in trigger_offline_retrieval
    _check_scihub_response(r, test_json=False)
  File "C:\Python39\lib\site-packages\sentinelsat\sentinel.py", line 1479, in _check_scihub_response
    raise ServerError(msg, response)
sentinelsat.exceptions.ServerError: HTTP status 500 Internal Server Error: UnsupportedOperationException : Error creating stream from file /mnt/s2al2a/dhus/incoming/x2/x1/x1/x1/S2A_MSIL2A_20210623T112121_N0300_R037_T29TNF_20210623T142829.zip
```

Code:
```python
from sentinelsat import SentinelAPI, read_geojson, geojson_to_wkt

api = SentinelAPI('myname', 'mypssword')
footprint = geojson_to_wkt(read_geojson('map.geojson'))
products = api.query(footprint,
                     platformname='Sentinel-2',
                     cloudcoverpercentage=(0, 10),
                     producttype='S2MSI2A',
                     relativeorbitnumber='37'
                     )
api.download_all(products)
```

**Comment by j08lue** [comment]
Yes, this is the same issue as #503. Please tell the Copernicus EO Support about these failing products and ask when they will fix it. Feel free to report here or on the other issue about what they say.
