### ISSUE TITLE
Handle query length limits automatically

### ISSUE THREAD

**Issue by daniel-j-h** [sentinelsat/sentinelsat#521]
Hey folks,

I'm on sentinelsat 1.0.1 sending geojson with the `geojson_to_wkt` function.

Some geojson objects seem to be too big in their WKT encoding for the server, and I'm
1. getting a 500 exception from the server
2. the server sending me the full java backtrace (?)

We know the server limit in sentinelsat, no? Can we either
- check the length automatically before we send the query to the server
- somehow notify the copernicus folks to not run into a 500 and not send the exception backtrace
- automatically turn geometries into their bounding box and search for the bounding box

I'm not 100% sure if querying for the geom's bounding box will always return the same results - thoughts?

Here is the full log.

```
Traceback (most recent call last):
  File "/home/python/.local/lib/python3.8/site-packages/sentinelsat/sentinel.py", line 1433, in _check_scihub_response
    response.raise_for_status()
  File "/home/python/.local/lib/python3.8/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://apihub.copernicus.eu/apihub/search?<radacted>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  <redacted>
  File "/home/python/.local/lib/python3.8/site-packages/sentinelsat/sentinel.py", line 216, in query
    response, count = self._load_query(query, formatted_order_by, limit, offset)
  File "/home/python/.local/lib/python3.8/site-packages/sentinelsat/sentinel.py", line 289, in _load_query
    products, count = self._load_subquery(query, order_by, limit, offset)
  File "/home/python/.local/lib/python3.8/site-packages/sentinelsat/sentinel.py", line 322, in _load_subquery
    _check_scihub_response(response, query_string=query)
  File "/home/python/.local/lib/python3.8/site-packages/sentinelsat/sentinel.py", line 1479, in _check_scihub_response
    raise ServerError(msg, response)
sentinelsat.exceptions.ServerError: HTTP status 500 Internal Server Error:
# HTTP Status 500 – Internal Server Error

* * *

 **Type** Exception Report

 **Message** Could not roll back Hibernate transaction; nested exception is
org.hibernate.TransactionException: Unable to rollback against JDBC Connection

 **Description** The server encountered an unexpected condition that prevented
it from fulfilling the request.

 **Exception**



    org.springframework.transaction.TransactionSystemException: Could not roll back Hibernate transaction; nested exception is org.hibernate.TransactionException: Unable to r
ollback against JDBC Connection
        org.springframework.orm.hibernate5.HibernateTransactionManager.doRollback(HibernateTransactionManager.java:659)
        org.springframework.transaction.support.AbstractPlatformTransactionManager.processRollback(AbstractPlatformTransactionManager.java:836)
        org.springframework.transaction.support.AbstractPlatformTransactionManager.rollback(AbstractPlatformTransactionManager.java:810)
        org.springframework.transaction.interceptor.TransactionAspectSupport.completeTransactionAfterThrowing(TransactionAspectSupport.java:649)
        org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:370)
        org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
        org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        com.sun.proxy.$Proxy133.authenticate(Unknown Source)
        org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:175)
        org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:168)
        org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        fr.gael.dhus.spring.security.filter.PreAuthFilter.doFilter(PreAuthFilter.java:89)
        org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)
        org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)
        org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
        org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
        org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
        org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
        org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
        org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)


**Root Cause**



    org.hibernate.TransactionException: Unable to rollback against JDBC Connection
        org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor.rollback(AbstractLogicalConnectionImplementor.java:122)
        org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.rollback(JdbcResourceLocalTransactio
nCoordinatorImpl.java:304)
        org.hibernate.engine.transaction.internal.TransactionImpl.rollback(TransactionImpl.java:142)
        org.springframework.orm.hibernate5.HibernateTransactionManager.doRollback(HibernateTransactionManager.java:656)
        org.springframework.transaction.support.AbstractPlatformTransactionManager.processRollback(AbstractPlatformTransactionManager.java:836)
        org.springframework.transaction.support.AbstractPlatformTransactionManager.rollback(AbstractPlatformTransactionManager.java:810)
        org.springframework.transaction.interceptor.TransactionAspectSupport.completeTransactionAfterThrowing(TransactionAspectSupport.java:649)
        org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:370)
        org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
        org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        com.sun.proxy.$Proxy133.authenticate(Unknown Source)
        org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:175)
        org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:168)
        org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        fr.gael.dhus.spring.security.filter.PreAuthFilter.doFilter(PreAuthFilter.java:89)
        org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)
        org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)
        org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
        org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
        org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
        org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
        org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
        org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)

**Root Cause**



    org.postgresql.util.PSQLException: This connection has been closed.
        org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:803)
        org.postgresql.jdbc.PgConnection.rollback(PgConnection.java:810)
        com.jolbox.bonecp.ConnectionHandle.rollback(ConnectionHandle.java:1272)
        sun.reflect.GeneratedMethodAccessor577.invoke(Unknown Source)
        sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        java.lang.reflect.Method.invoke(Method.java:498)
        org.springframework.jdbc.datasource.LazyConnectionDataSourceProxy$LazyConnectionInvocationHandler.invoke(LazyConnectionDataSourceProxy.java:385)
        com.sun.proxy.$Proxy66.rollback(Unknown Source)
        org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor.rollback(AbstractLogicalConnectionImplementor.java:116)
        org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.rollback(JdbcResourceLocalTransactio
nCoordinatorImpl.java:304)
        org.hibernate.engine.transaction.internal.TransactionImpl.rollback(TransactionImpl.java:142)
        org.springframework.orm.hibernate5.HibernateTransactionManager.doRollback(HibernateTransactionManager.java:656)
        org.springframework.transaction.support.AbstractPlatformTransactionManager.processRollback(AbstractPlatformTransactionManager.java:836)
        org.springframework.transaction.support.AbstractPlatformTransactionManager.rollback(AbstractPlatformTransactionManager.java:810)
        org.springframework.transaction.interceptor.TransactionAspectSupport.completeTransactionAfterThrowing(TransactionAspectSupport.java:649)
        org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:370)
        org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
        org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        com.sun.proxy.$Proxy133.authenticate(Unknown Source)
        org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:175)
        org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:168)
        org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        fr.gael.dhus.spring.security.filter.PreAuthFilter.doFilter(PreAuthFilter.java:89)
        org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)
        org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)
        org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
        org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
        org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
        org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
        org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
        org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)


**Note** The full stack trace of the root cause is available in the server
logs.

* * *

### Apache Tomcat/8.0.53
The query string is too long and will likely cause a bad DHuS response.
Traceback (most recent call last):
  File "/home/python/.local/lib/python3.8/site-packages/sentinelsat/sentinel.py", line 1433, in _check_scihub_response
    response.raise_for_status()
  File "/home/python/.local/lib/python3.8/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://apihub.copernicus.eu/apihub/search?<redacted>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  <redacted>
  File "/home/python/.local/lib/python3.8/site-packages/sentinelsat/sentinel.py", line 216, in query
    response, count = self._load_query(query, formatted_order_by, limit, offset)
  File "/home/python/.local/lib/python3.8/site-packages/sentinelsat/sentinel.py", line 289, in _load_query
    products, count = self._load_subquery(query, order_by, limit, offset)
  File "/home/python/.local/lib/python3.8/site-packages/sentinelsat/sentinel.py", line 322, in _load_subquery
    _check_scihub_response(response, query_string=query)
  File "/home/python/.local/lib/python3.8/site-packages/sentinelsat/sentinel.py", line 1473, in _check_scihub_response
    raise QueryLengthError(msg, response)
sentinelsat.exceptions.QueryLengthError: Server was unable to process the query due to its excessive length (approximately 1.07x times the maximum allowed). Consider using SentinelAPI.check_query_length() for client-side validation of the query string length.
```

**Comment by valgur** [comment]
As you probably already noticed, `sentinelsat` already checks the query length to display the warning message you are seeing, but it's only done after a server-side error rather than preemptively, as you are suggesting. It's not a bad idea at all, but I don't think it can be implemented reliably enough. The query length limit is very arbitrary, undocumented and not fixed in time. Plus, the main scihub.copernicus.eu endpoint is not the only one that sentinelsat supports.

> somehow notify the copernicus folks to not run into a 500 and not send the exception backtrace

That's a good idea, I agree. The backtrace does not provide any useful additional info and is just noise. We should hide it.

 > automatically turn geometries into their bounding box and search for the bounding box
I'm not 100% sure if querying for the geom's bounding box will always return the same results - thoughts?

It would generally definitely not produce the same results, especially for bigger geometries. I think doing this automatically would be too easy to miss and could produce unexpected results. We could however display a hint about the geometry being the likely cause of the query length issue and providing a bounding box as an alternative geometry to try. A PR for that would be welcome.

**Comment by daniel-j-h** [comment]
> The query length limit is very arbitrary, undocumented and not fixed in time.

![wat](https://user-images.githubusercontent.com/527241/126711177-627929c7-0cf7-41bf-a8da-fc098731a741.jpg)

I feel really sorry for you folks having to deal with all this upstream mess :crying_cat_face: 

After reading your comment, I think all we can realistically do here is flag it with the copernicus folks so they can fix the 500 issues.

Anyone got a handle to cc or ping?
