### ISSUE TITLE
Unable to download/query via sentinelsat.

### ISSUE THREAD

**Issue by zwxlyy1995** [sentinelsat/sentinelsat#560]
Hi,I am unable to download or query images via sentinelsat, I am getting following Error:
```
Traceback (most recent call last):
  File "e:/RS_DATA/zwx-Sentinel-Toolbox/a.py", line 7, in <module>
    api.download('99102122-0c4c-4083-976d-c64917b9e7f8')
  File "C:\Users\lenovo\.conda\envs\download\lib\site-packages\sentinelsat\sentinel.py", line 591, in download
    return downloader.download(id, directory_path)
  File "C:\Users\lenovo\.conda\envs\download\lib\site-packages\sentinelsat\download.py", line 135, in download
    product_info = self.api.get_product_odata(id)
  File "C:\Users\lenovo\.conda\envs\download\lib\site-packages\sentinelsat\sentinel.py", line 511, in get_product_odata
    response = self.session.get(url)
  File "C:\Users\lenovo\.conda\envs\download\lib\site-packages\requests\sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\lenovo\.conda\envs\download\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\lenovo\.conda\envs\download\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\lenovo\.conda\envs\download\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='scihub.copernicus.eu', port=443): Max retries exceeded with url: /dhus/odata/v1/Products('99102122-0c4c-4083-976d-c64917b9e7f8')?$format=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EBF6948190>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
``` 
my code is here:
```python
from sentinelsat import SentinelAPI, read_geojson, geojson_to_wkt
from datetime import date

api = SentinelAPI('username', 'password', 'https://scihub.copernicus.eu/dhus')

# download single scene by known product id
api.download('99102122-0c4c-4083-976d-c64917b9e7f8')
```
Could anyone help me?

**Comment by domino1989-lab** [comment]
it seems that we can not connect to the server, I don`t know how to solve this
