### ISSUE TITLE
Downloading problem

### ISSUE THREAD

**Issue by ziqing97** [sentinelsat/sentinelsat#578]
Hi,
I was  tring to download sentinel-3 data using  sentinelsat with following codes and it didn't work:

```python
from sentinelsat import SentinelAPI, read_geojson, geojson_to_wkt
api =SentinelAPI (user, passwd, 'https://scihub.copernicus.eu/dhus/#/home')
                  
products = api.query(filename = '*S3A_SR_2_LAN____*O_NT_004*', date=('2022-08-10T00:00:00.000Z', '2022-08-12T00:00:00.000Z'))
api.download_all(products, '\\\\gis-cifs.tik.uni-stuttgart.de\\GIS\\Altimetry data\\Sentinel-3A')
```
I got the following messsage repeatly and cannot figure it out why

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\sentinelsat\download.py", line 395, in _init_statuses
    info = self.api.get_product_odata(pid)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sentinelsat\sentinel.py", line 511, in get_product_odata
    self._check_scihub_response(response)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sentinelsat\sentinel.py", line 1065, in _check_scihub_response
    raise SentinelAPIError(msg, response)
sentinelsat.exceptions.SentinelAPIError: HTTP status 200:

Getting product info for 7b82eb1b-ac5f-4d0d-a87e-b8fb0ef45554 failed, can't download: Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\sentinelsat\sentinel.py", line 1019, in _check_scihub_response
    response.json()
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\sentinelsat\download.py", line 395, in _init_statuses
    info = self.api.get_product_odata(pid)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sentinelsat\sentinel.py", line 511, in get_product_odata
    self._check_scihub_response(response)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sentinelsat\sentinel.py", line 1065, in _check_scihub_response
    raise SentinelAPIError(msg, response)
sentinelsat.exceptions.SentinelAPIError: HTTP status 200:
```

Thanks in advance for your help.

**Comment by j08lue** [comment]
Why do you change the API URL to `'https://scihub.copernicus.eu/dhus/#/home'`?

Does it work if you do not do that?

**Comment by ziqing97** [comment]
> Why do you change the API URL to `'https://scihub.copernicus.eu/dhus/#/home'`?
> 
> Does it work if you do not do that?

Yeah, you're right. I did that  because some collegues downloaded the data before from the this site and I believe it did work.

Now everything is fine after I set the URL to the default one.

Thanks very much!
