### ISSUE TITLE
the CLI returns too many erors in the first try

### ISSUE THREAD

**Issue by soroushyasini** [sentinelsat/sentinelsat#584]
hello , i an trying to download a part of sentinel-1 data ( cropped by geo.json )
  i enter the following command and this is the return :

```
(base) soroush@sororush-dell:~$ sentinelsat -u soroushyasini -p heisinvincible -g search_polygon.geojson -s 20210101 -e 20221231 -d --producttype SLC -q "orbitdirection=Descending" --url "https://apihub.copernicus.eu/apihub"
Traceback (most recent call last):
  File "/home/soroush/anaconda3/bin/sentinelsat", line 8, in <module>
    sys.exit(cli())
  File "/home/soroush/anaconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/soroush/anaconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/soroush/anaconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/soroush/anaconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/soroush/sentinelsat/sentinelsat/scripts/cli.py", line 349, in cli
    search_kwargs["area"] = geojson_to_wkt(read_geojson(geometry))
  File "/home/soroush/sentinelsat/sentinelsat/sentinel.py", line 1120, in read_geojson
    return geojson.load(f)
  File "/home/soroush/anaconda3/lib/python3.9/site-packages/geojson/codec.py", line 40, in load
    return json.load(fp,
  File "/home/soroush/anaconda3/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/home/soroush/anaconda3/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/home/soroush/anaconda3/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/soroush/anaconda3/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

what does it mean ?

**Comment by j08lue** [comment]
```python
search_kwargs["area"] = geojson_to_wkt(read_geojson(geometry))
```

Looks like your input `geometry` is not valid JSON.

**Comment by soroushyasini** [comment]
thanks! yes i checked out the GEOJSON file , it was corrupted.
