### ISSUE TITLE
 I have error when download usin sentinelsat API 

### ISSUE THREAD

**Issue by Asmaa-ashraf88** [sentinelsat/sentinelsat#596]
```python
from sentinelsat import SentinelAPI, read_geojson, geojson_to_wkt
from datetime import date
import os




dir_path = r'D:\Download\3-Geojson'

 # Iterate directory
for file in os.listdir(dir_path):
            # check only text files
            if file.endswith('.geojson'):

                geojsonInput = str(dir_path) +'\\' +str(file)

                print(geojsonInput)
                # connect to the API
                api = SentinelAPI('asmaaabd_elsalam', '...', 'https://apihub.copernicus.eu/apihub')

                footprint = geojson_to_wkt(read_geojson(geojsonInput))
                products = api.query(footprint,
                                     date=('20230509', date(2023, 5, 11)),
                                     platformname='Sentinel-2',
                                     processinglevel='Level-2A',
                                     #area_relation="IsWithin",
                                     # cloudcoverpercentage=(0, 50),
                                     # tileid='tile_name',
                                     )

                products_df = api.to_dataframe(products)

                print(products_df)
               api.download_all(products , directory_path =r"D:\Download\AllEGY09-011-052023")


```

when run this it work, but some time have issues :

```
C:\Users\asmaa.ashraf\AppData\Local\Programs\Python\Python311\python.exe D:\Download\API_Download_Script\sentinel_tile.py 
D:\3-Geojson\S2_Tiling_EGY_AGRI_36QUK.geojson
Traceback (most recent call last):
  File "C:\Users\asmaa.ashraf\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asmaa.ashraf\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "C:\Users\asmaa.ashraf\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "C:\Users\asmaa.ashraf\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "C:\Users\asmaa.ashraf\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 635, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asmaa.ashraf\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 776, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "C:\Users\asmaa.ashraf\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\ssl_.py", line 466, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asmaa.ashraf\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\ssl_.py", line 510, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asmaa.ashraf\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asmaa.ashraf\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1075, in _create
    self.do_handshake()
  File "C:\Users\asmaa.ashraf\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\asmaa.ashraf\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\asmaa.ashraf\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\asmaa.ashraf\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asmaa.ashraf\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\asmaa.ashraf\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asmaa.ashraf\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "C:\Users\asmaa.ashraf\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "C:\Users\asmaa.ashraf\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "C:\Users\asmaa.ashraf\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 635, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asmaa.ashraf\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 776, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "C:\Users\asmaa.ashraf\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\ssl_.py", line 466, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asmaa.ashraf\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\ssl_.py", line 510, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asmaa.ashraf\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asmaa.ashraf\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1075, in _create
    self.do_handshake()
  File "C:\Users\asmaa.ashraf\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Download\API_Download_Script\sentinel_tile.py", line 42, in <module>
    downlod(dir_path)
  File "D:\Download\API_Download_Script\sentinel_tile.py", line 23, in downlod
    products = api.query(footprint,
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asmaa.ashraf\sentinelsat\sentinelsat\sentinel.py", line 282, in query
    response, count = self._load_query(query, formatted_order_by, limit, offset)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asmaa.ashraf\sentinelsat\sentinelsat\sentinel.py", line 355, in _load_query
    products, count = self._load_subquery(query, order_by, limit, offset)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asmaa.ashraf\sentinelsat\sentinelsat\sentinel.py", line 388, in _load_subquery
    response = self.session.get(url, params={"q": query.encode("latin1")})
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asmaa.ashraf\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asmaa.ashraf\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asmaa.ashraf\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asmaa.ashraf\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

Process finished with exit code 1

```

I can't detect the reason for this error

**Comment by j08lue** [comment]
Looks like the server aborts the connection for no apparent reason. Not much we or you can do about that, I am afraid. Just retry.
